spring:
  datasource:
    url: ${BANK_SERVICE_DATABASE_URL}
    username: ${BANK_SERVICE_DATABASE_USERNAME}
    password: ${BANK_SERVICE_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    access-token:
      private-key: ${BANK_SERVICE_ACCESS_TOKEN_PRIVATE_KEY}
    refresh-token:
      private-key: ${BANK_SERVICE_REFRESH_TOKEN_PRIVATE_KEY}
