server:
  port: 8000

spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

logging:
  level:
    root: INFO
