spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/bank_database
    username: developer
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

app:
  jwt:
    access-token:
      private-key: MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDBt8mtM+jAKlIdAXScm4nGomFA83nVrH3m3AC6IrjH/Q9HBb4cl7HyBLycRmUK+N0OhZANiAAQiLurUtCYWSuhNtceHyGwTugLE9yntCn81RTSfXk+9iXsNHRYb/VX+kaXMNvWcyaj3cNeqZc+vcWa2ccCqJzR9wRwEAxuIf2+yTbwEWog6yhsS/55vPHN9taeIX83vVzg=
      public-key: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEIi7q1LQmFkroTbXHh8hsE7oCxPcp7Qp/NUU0n15PvYl7DR0WG/1V/pGlzDb1nMmo93DXqmXPr3FmtnHAqic0fcEcBAMbiH9vsk28BFqIOsobEv+ebzxzfbWniF/N71c4
      expiration-millis: 1800000
  encryption:
    key: MXcNP1unamARqbDU4eGY/j9DrFW/8eYwQpNsnul8a+0=
  hmac:
    key: I8KOq6SJY+FkPLna5goGPA22IN+T1fYFahxeTkAOoXs=
